name: Lighthouse CI
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, master ]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v3
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run
        run: npm run lhci

